### ISSUE TITLE
重新处理Detail页面

### ISSUE THREAD

**Issue by gaosboy** [gaosboy/iOSSF#10]
JS处理Detail页面，变好看一点

**Comment by agassiyzh** [comment]
你好勤快啊

发自我的 iPhone

在 2012-12-23，下午5:55，Jiajun notifications@github.com 写道：

JS处理Detail页面，变好看一点

—
Reply to this email directly or view it on
GitHubhttps://github.com/gaosboy/iOSSF/issues/10.
