### ISSUE TITLE
QuestionList Table 滑动略卡

### ISSUE THREAD

**Issue by agassiyzh** [gaosboy/iOSSF#2]
测试和自己写的NavgationController有点，继承自UIViewController滑动快很多。

然后我去看看那些类。

**Comment by gaosboy** [comment]
敢不敢语言通顺点

---

Jianjun. Gao, From iPhone
http://gaosboy.com/

**Comment by agassiyzh** [comment]
我把，SFRootViewController继承自UIViewController后，流畅很多。

现在正在看SFSlideNavViewController这个类。

**Comment by agassiyzh** [comment]
@gaosboy 找到问题了。是UMSlideNavigationController的contentView设置了阴影，每次table滑动重绘的时候造成卡顿。等我提交代码。

**Comment by agassiyzh** [comment]
github 太牛逼了，现在提交中有fix字样，直接关闭issuse。之前只是＃管理issuse。大赞！

**Comment by gaosboy** [comment]
a79af44这个版本搞定了

**Comment by agassiyzh** [comment]
@gaosboy 在commit的时候内容中添加 # 加issuse号就自动会在这里出现的，好方便。
like this https://github.com/gaosboy/iOSSF/issues/2#commit-ref-dbd87d8
