### ISSUE TITLE
关于SFSlideNavViewController中loadedRootViewControllers的问题

### ISSUE THREAD

**Issue by flankerhqd** [gaosboy/iOSSF#25]
Hi! 首先感谢gaosboy等前辈能将这样优秀的客户端开源~

我是ios新手，最近在研读学习iossf的代码。在SFSlideNavViewController中看到一个property loadedRootViewController，结合上下文看这个property似乎只在viewDidLoad中出现，并且也只是初始化赋值操作。注释掉那段代码后app似乎也能正常运行，于是就不是很明白这个property的作用，有什么其他的考虑么？

thx~~

**Comment by gaosboy** [comment]
注释里有，用来记录已经载入的VC，避免重复刷新

**Comment by gaosboy** [comment]
之前有这样的逻辑，点击侧导航的某一个Cell，改Cell要返回RootViewController。
这个逻辑现在去掉了，所以这个属性就没用了，但是我觉得这些东西还是应该记录下来，没准什么时候就用到~~~

**Comment by flankerhqd** [comment]
Got it, thanks~
